# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "prepare"
  - "build"
  - "deploy"

steps:

  report_build:
    title: Report build to port
    stage: prepare
    image: kostiscodefresh/port-inject
    working_directory: IMAGE_WORK_DIR
    environment:
    - BLUEPRINT_IDENTIFIER=build
    - ENTITY_IDENTIFIER=${{CF_BUILD_ID}} 
    - ENTITY_TITLE=${{CF_PIPELINE_NAME}}
    - OPERATION=upsert
    - ENTITY_PROPERTIES={"details":"${{CF_BUILD_URL}}","initiator":"${{CF_BUILD_INITIATOR}}"}
    - ENTITY_RELATIONS={"for":"${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"}
    
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: "main"
    stage: "prepare"

  build_step:
    title: "Building Docker image"
    type: "build"
    image_name: "kostiscodefresh/port-simple-app"
    tag: main
    tags:
    - "latest"
    - "v1.0"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: dockerhub
  deploy_to_k8:
    title: Deploying to QA cluster
    type: deploy
    stage: "deploy"
    kind: kubernetes 
    cluster:  qa-virtual-cluster
    namespace: default
    file_path: ./manifest.yml
    env:
     name: my-qa-env
     endpoints:
     - name: app
       url: https://qa.port.sales-dev.codefresh.io
     type: kubernetes
     change: ${{CF_COMMIT_MESSAGE}}
     filters:
     - cluster: qa-virtual-cluster
       namespace: default   
  report_deployment:
    stage: deploy
    title: Report deployment to port
    image: kostiscodefresh/port-inject
    working_directory: IMAGE_WORK_DIR
    environment:
    - BLUEPRINT_IDENTIFIER=deployment
    - ENTITY_IDENTIFIER=${{CF_BUILD_ID}} 
    - ENTITY_TITLE=${{CF_PIPELINE_NAME}}
    - OPERATION=upsert
    - ENTITY_PROPERTIES={"details":"${{CF_BUILD_URL}}","gitHash":"${{CF_SHORT_REVISION}}","version":"1.0"}
    - ENTITY_RELATIONS={"for":"${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}","target":"qa"} 

